### ISSUE TITLE
[TODO] Setting up environment for PySIDT

### ISSUE THREAD

**Issue by hwpang** [zadorlab/PySIDT#3]
- [x] Get https://github.com/ReactionMechanismGenerator/molecule/tree/ts_len_improvements branch merged into `main`
- [x] Build https://github.com/ReactionMechanismGenerator/molecule to be conda package
- [x] Add a `pyproject.toml` for PySIDT

**Comment by hwpang** [comment]
@mjohnson541 I looked into setting up github workflow for tests but we need these to be resolved first.
